export const COMMON_GLOBAL_CSS_FILELOCATIONS = [
  "",
  "src/",
  "src/styles/",
  "src/assets/css/",
  "src/assets/styles/",
  "src/assets/",
  "styles/",
  "css/",
  "public/",
  "public/assets/css/",
  "public/assets/styles/",
  "public/assets/",
  "public/styles/",
  "public/css/",
];

export const COMMON_CSS_FILES = [
  "index.css",
  "index.scss",
  "index.sass",
  "index.less",
  "index.styl",
  "index.stylus",
  "index.pcss",

  "style.css",
  "style.scss",
  "style.sass",
  "style.less",
  "style.styl",
  "style.stylus",
  "style.pcss",

  "styles.css",
  "styles.scss",
  "styles.sass",
  "styles.less",
  "styles.styl",
  "styles.stylus",
  "styles.pcss",

  "global.css",
  "global.scss",
  "global.sass",
  "global.less",
  "global.styl",
  "global.stylus",
  "global.pcss",

  "globals.css",
  "globals.scss",
  "globals.sass",
  "globals.less",
  "globals.styl",
  "globals.stylus",
  "globals.pcss",

  "app.css",
  "app.scss",
  "app.sass",
  "app.less",
  "app.styl",
  "app.stylus",
  "app.pcss",

  "main.css",
  "main.scss",
  "main.sass",
  "main.less",
  "main.styl",
  "main.stylus",
  "main.pcss",

  "tailwind.css",
  "tailwind.scss",
  "tailwind.sass",
  "tailwind.less",
  "tailwind.styl",
  "tailwind.stylus",
];
